sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 8
  - 10
script: npm run setup && yarn dist
deploy:
  local_dir: dist
  fqdn: hyperapp-fusebox.deployable.site
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
